
ENABLE_LINTERS:
  - REPOSITORY_GITLEAKS
  - REPOSITORY_KICS
  - BASH_SHELLCHECK
  - PYTHON_BLACK
  - PYTHON_FLAKE8
  - PYTHON_ISORT
  - ACTION_ACTIONLINT
  - MARKDOWN_MARKDOWNLINT
  - MAKEFILE_CHECKMAKE

BASH_SHELLCHECK_ARGUMENTS: "disable=SC2128,SC1091"