
ENABLE_LINTERS:
  - REPOSITORY_GITLEAKS
  - BASH_SHELLCHECK
  - PYTHON_BLACK
  - PYTHON_FLAKE8
  - PYTHON_ISORT
  - ACTION_ACTIONLINT
  - DOCKERFILE_HADOLINT
  - MARKDOWN_MARKDOWNLINT
  - MAKEFILE_CHECKMAKE